name: Regression build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build-app:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        common-features: ['Order nodes,Zoom at,Auto arrange,Dataflow engine,Selectable nodes,Context menu,Minimap,Reroute']
        include:
          - stack: angular
            version: 12
            features: 'Angular render'
          - stack: angular
            version: 13
            features: 'Angular render'
          - stack: angular
            version: 14
            features: 'Angular render'
          - stack: angular
            version: 15
            features: 'Angular render'
          - stack: angular
            version: 16
            features: 'Angular render'
          - stack: angular
            version: 17
            features: 'Angular render'
          - stack: react
            version: 16
            features: 'React render'
          - stack: react
            version: 17
            features: 'React render'
          - stack: react
            version: 18
            features: 'React render'
          - stack: vue
            version: 2
            features: 'Vue render'
          - stack: vue
            version: 3
            features: 'Vue render'
          - stack: svelte
            version: 3
            features: 'Svelte render'
          - stack: svelte
            version: 4
            features: 'Svelte render'

    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
    - name: Install Rete Kit
      run: npm i -g rete-kit
    - name: Rete Kit version
      run: rete-kit -V
    - name: Test
      run: echo  ${{ matrix.stack }}${{ matrix.version }} ${{ matrix.common-features }} ${{ matrix.features }}  # rete-kit app -n app -s ${{ matrix.stack }} -v ${{ matrix.version }} 
